version: '3.9'
services:
  tmod:
      build: .
      tty: true
      stdin_open: true
      container_name: 'tmod'
      ports:
          - '7777:7777'
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./Mods:/terraria/tModLoader/Mods
          - ./Worlds:/terraria/tModLoader/Worlds
          - ./logs:/terraria-server/tModLoader-Logs
          - ./config.txt:/terraria-server/config.txt
      environment:
          - TMOD_SHUTDOWN_MSG="See ya!"